# Generated by Django 5.1.3 on 2025-04-28 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration", models.IntegerField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("AC", "Action"),
                            ("CO", "Comedy"),
                            ("DR", "Drama"),
                            ("HO", "Horror"),
                            ("SF", "Sci-Fi"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("release_date", models.DateField()),
                ("poster", models.ImageField(upload_to="movies/")),
                ("rating", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_number", models.PositiveIntegerField()),
                ("capacity", models.PositiveIntegerField()),
                (
                    "screen_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("imax", "IMAX"),
                            ("4dx", "4DX"),
                            ("dolby", "Dolby Cinema"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Theater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=15)),
                ("image", models.ImageField(upload_to="theaters/")),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("payment_status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookedSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.booking"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                ("row", models.CharField(max_length=2)),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.screen"
                    ),
                ),
            ],
            options={
                "unique_together": {("screen", "row", "seat_number")},
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="seats",
            field=models.ManyToManyField(through="movies.BookedSeat", to="movies.seat"),
        ),
        migrations.AddField(
            model_name="bookedseat",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.seat"
            ),
        ),
        migrations.CreateModel(
            name="Showtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.theater"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="showtime",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.showtime"
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.theater"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="theaters",
            field=models.ManyToManyField(
                through="movies.Showtime", to="movies.theater"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookedseat",
            unique_together={("booking", "seat")},
        ),
        migrations.AlterUniqueTogether(
            name="screen",
            unique_together={("theater", "screen_number")},
        ),
    ]
