# Generated by Django 5.2 on 2025-04-25 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                ("row", models.CharField(max_length=2)),
                ("is_booked", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.RemoveField(
            model_name="booking",
            name="seats",
        ),
        migrations.CreateModel(
            name="BookedSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.booking"
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.seat"
                    ),
                ),
            ],
            options={
                "unique_together": {("booking", "seat")},
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="seats",
            field=models.ManyToManyField(through="movies.BookedSeat", to="movies.seat"),
        ),
    ]
