# Generated by Django 5.1.3 on 2025-04-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.CharField(
                choices=[
                    ("EN", "English"),
                    ("SI", "Sinhala"),
                    ("TA", "Tamil"),
                    ("OT", "Other"),
                ],
                default="EN",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="movies.genre"),
        ),
    ]
