# Generated by Django 5.1.3 on 2025-04-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_seat_booking_payment_status_booking_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
