# Generated by Django 5.1.3 on 2025-05-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_genre_remove_movie_genre_movie_language_movie_genres"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-booking_date"]},
        ),
    ]
