# Generated by Django 5.1.3 on 2025-05-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_booking_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
