# Generated by Django 5.2 on 2025-04-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('showtime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='movie_banners/')),
            ],
        ),
    ]
