# Generated by Django 5.1.3 on 2025-05-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
