# Generated by Django 5.1.3 on 2025-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0002_userprofile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rewards_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
