# Generated by Django 5.1.3 on 2025-05-03 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking_system",
            "0005_remove_reward_code_prefix_remove_reward_expiry_days_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userreward",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userreward",
            name="reward_name",
            field=models.CharField(default="Default Reward", max_length=100),
        ),
        migrations.AddField(
            model_name="userreward",
            name="reward_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userreward",
            name="code",
            field=models.CharField(default="CODE-0000", max_length=15),
        ),
        migrations.AlterField(
            model_name="userreward",
            name="reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking_system.reward",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userreward",
            unique_together={("user", "reward_name")},
        ),
    ]
