# Generated by Django 5.1.3 on 2025-05-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0006_alter_userreward_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreward",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userreward",
            name="code",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
